// flow-typed signature: d282f65ad3d5e4e4e3643abf6f6e0e16
// flow-typed version: <<STUB>>/qr-image_v^3.2.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qr-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qr-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qr-image/lib/crc32' {
  declare module.exports: any;
}

declare module 'qr-image/lib/crc32buffer' {
  declare module.exports: any;
}

declare module 'qr-image/lib/encode' {
  declare module.exports: any;
}

declare module 'qr-image/lib/errorcode' {
  declare module.exports: any;
}

declare module 'qr-image/lib/matrix' {
  declare module.exports: any;
}

declare module 'qr-image/lib/png' {
  declare module.exports: any;
}

declare module 'qr-image/lib/qr-base' {
  declare module.exports: any;
}

declare module 'qr-image/lib/qr' {
  declare module.exports: any;
}

declare module 'qr-image/lib/vector' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qr-image/lib/crc32.js' {
  declare module.exports: $Exports<'qr-image/lib/crc32'>;
}
declare module 'qr-image/lib/crc32buffer.js' {
  declare module.exports: $Exports<'qr-image/lib/crc32buffer'>;
}
declare module 'qr-image/lib/encode.js' {
  declare module.exports: $Exports<'qr-image/lib/encode'>;
}
declare module 'qr-image/lib/errorcode.js' {
  declare module.exports: $Exports<'qr-image/lib/errorcode'>;
}
declare module 'qr-image/lib/matrix.js' {
  declare module.exports: $Exports<'qr-image/lib/matrix'>;
}
declare module 'qr-image/lib/png.js' {
  declare module.exports: $Exports<'qr-image/lib/png'>;
}
declare module 'qr-image/lib/qr-base.js' {
  declare module.exports: $Exports<'qr-image/lib/qr-base'>;
}
declare module 'qr-image/lib/qr.js' {
  declare module.exports: $Exports<'qr-image/lib/qr'>;
}
declare module 'qr-image/lib/vector.js' {
  declare module.exports: $Exports<'qr-image/lib/vector'>;
}
