// flow-typed signature: e2349df162ddfad113dd9fcbfc6d39d5
// flow-typed version: <<STUB>>/react-chrome-redux_v^1.5.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-chrome-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-chrome-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-chrome-redux/lib/alias/alias' {
  declare module.exports: any;
}

declare module 'react-chrome-redux/lib/constants/index' {
  declare module.exports: any;
}

declare module 'react-chrome-redux/lib/index' {
  declare module.exports: any;
}

declare module 'react-chrome-redux/lib/store/Store' {
  declare module.exports: any;
}

declare module 'react-chrome-redux/lib/wrap-store/shallowDiff' {
  declare module.exports: any;
}

declare module 'react-chrome-redux/lib/wrap-store/wrapStore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-chrome-redux/lib/alias/alias.js' {
  declare module.exports: $Exports<'react-chrome-redux/lib/alias/alias'>;
}
declare module 'react-chrome-redux/lib/constants/index.js' {
  declare module.exports: $Exports<'react-chrome-redux/lib/constants/index'>;
}
declare module 'react-chrome-redux/lib/index.js' {
  declare module.exports: $Exports<'react-chrome-redux/lib/index'>;
}
declare module 'react-chrome-redux/lib/store/Store.js' {
  declare module.exports: $Exports<'react-chrome-redux/lib/store/Store'>;
}
declare module 'react-chrome-redux/lib/wrap-store/shallowDiff.js' {
  declare module.exports: $Exports<'react-chrome-redux/lib/wrap-store/shallowDiff'>;
}
declare module 'react-chrome-redux/lib/wrap-store/wrapStore.js' {
  declare module.exports: $Exports<'react-chrome-redux/lib/wrap-store/wrapStore'>;
}
