// flow-typed signature: d2118a917382e4423ffea9b3801671dd
// flow-typed version: <<STUB>>/redux-test-utils_v^0.2.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-test-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-test-utils/dist/index' {
  declare module.exports: any;
}

declare module 'redux-test-utils/dist/utils/__tests__/DispatchMockSpec' {
  declare module.exports: any;
}

declare module 'redux-test-utils/dist/utils/__tests__/equals.test' {
  declare module.exports: any;
}

declare module 'redux-test-utils/dist/utils/__tests__/StoreMockSpec' {
  declare module.exports: any;
}

declare module 'redux-test-utils/dist/utils/DispatchMock' {
  declare module.exports: any;
}

declare module 'redux-test-utils/dist/utils/equals' {
  declare module.exports: any;
}

declare module 'redux-test-utils/dist/utils/StoreMock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-test-utils/dist/index.js' {
  declare module.exports: $Exports<'redux-test-utils/dist/index'>;
}
declare module 'redux-test-utils/dist/utils/__tests__/DispatchMockSpec.js' {
  declare module.exports: $Exports<'redux-test-utils/dist/utils/__tests__/DispatchMockSpec'>;
}
declare module 'redux-test-utils/dist/utils/__tests__/equals.test.js' {
  declare module.exports: $Exports<'redux-test-utils/dist/utils/__tests__/equals.test'>;
}
declare module 'redux-test-utils/dist/utils/__tests__/StoreMockSpec.js' {
  declare module.exports: $Exports<'redux-test-utils/dist/utils/__tests__/StoreMockSpec'>;
}
declare module 'redux-test-utils/dist/utils/DispatchMock.js' {
  declare module.exports: $Exports<'redux-test-utils/dist/utils/DispatchMock'>;
}
declare module 'redux-test-utils/dist/utils/equals.js' {
  declare module.exports: $Exports<'redux-test-utils/dist/utils/equals'>;
}
declare module 'redux-test-utils/dist/utils/StoreMock.js' {
  declare module.exports: $Exports<'redux-test-utils/dist/utils/StoreMock'>;
}
