export const TRANSACTION_URL = '/transaction'
export const SIGN_MESSAGE_URL = '/sign-message'

export const WELCOME_URL = '/welcome'
export const DOWNLOAD_APPS_URL = '/download-apps'
export const ACCOUNT_URL = '/account'
export const PASSWORD_URL = '/password'
export const CREATE_PASSWORD_URL = '/create-password'
export const CONFIRM_PASSWORD_URL = '/confirm-password'
export const CHANGE_PASSWORD_URL = '/change-password'
export const WHITELIST_URL = '/whitelist'
export const LOCKING_URL = '/locking'
export const RESYNC_TOKEN_URL = '/resync-token'
export const ABOUT_URL = '/about'
export const REPLACE_RECOVERY_PHRASE_URL = '/replace-recovery-phrase'
export const PAYMENT_TOKEN_URL = '/payment-token'
